version: '3'
services:
  apollo-test:
    container_name: apollo-test
    image: apollo:test
    build:
      context: .
    ports:
      - "1972:8000"
    volumes:
      - .:/home/apollo/apollo
      - /home/apollo/apollo/apollo.egg-info
    links:
      - db-test
    depends_on:
      - db-test
    tty: true
    stdin_open: true
    entrypoint: "/bin/bash"
    command: >
      -c "../util/wait-for-it.sh db:5432 &&
      alembic -c test.ini upgrade heads &&
      coverage run --source apollo -m pytest &&
      coverage report -m &&
      coverage xml"
  db-test:
    container_name: apollo-test-db
    image: postgres:12
    ports:
      - "1974:5432"
    environment:
      - POSTGRES_USER=apollo
      - POSTGRES_PASSWORD=testing123
      - POSTGRES_DB=apollo-test
