version: "3"
services:
  apollo-test:
    container_name: apollo-test
    image: apollo:test
    build:
      context: .
    ports:
      - "1974:8000"
    volumes:
      - .:/home/apollo/apollo
      - /home/apollo/apollo/apollo.egg-info
    links:
      - db-test
      - redis-test
    depends_on:
      - db-test
    tty: true
    stdin_open: true
    entrypoint: "/bin/bash"
    command: >
      -c "../util/wait-for-it.sh db-test:5432 &&
      alembic -c test.ini upgrade heads &&
      coverage run --source apollo -m pytest &&
      coverage report -m &&
      coverage xml"
    networks:
      - apollo-test-network
  db-test:
    container_name: apollo-test-db
    image: postgres:12
    ports:
      - "1975:5432"
    environment:
      - POSTGRES_USER=apollo
      - POSTGRES_PASSWORD=testing123
      - POSTGRES_DB=apollo-test
    networks:
      - apollo-test-network
  redis-test:
    container_name: apollo-test-cache
    image: redis:6
    networks:
      - apollo-test-network

networks:
  apollo-test-network:
