name: Test

on:
  pull_request:
    branches:
    - develop
    - master
  push:
    branches:
    - develop
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test with pytest
        run: docker-compose -f test-compose.yml up --exit-code-from apollo-test apollo-test

      - name: Upload coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CODECOV_BASH_URL: https://codecov.io/bash
          CODECOV_SHASUM_URL: https://raw.githubusercontent.com/codecov/codecov-bash/master/SHA256SUM
        run: |
          curl -s $CODECOV_BASH_URL > codecov
          chmod +x codecov
          curl --location --show-error --silent -s $CODECOV_SHASUM_URL | head -1 | sha256sum --check \
              && ./codecov
